# fly.toml app configuration file generated for weight-tracker on 2023-07-30T17:37:07+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "weight-tracker"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
